### ISSUE TITLE
sqlite.close not found

### ISSUE THREAD

**Issue by rhaker** [jbrodriguez/react-native-android-sqlite#3]
Thanks for putting this together. I'm just doing some initial tests and it seems that sqlite.close is not found in the current build. It exists in DBManager.java, but not in your javascript module definition.

If I add the following code to index.android.js, the function is found:

``` javascript
close: function(
        callback?: ?(error: ?Error, result: ?string) => void
    ): Promise {
        return new Promise((resolve, reject) => {
            DBManager.close(function(errors, result) {
                callback && callback((errors && convertError(errors[0])) || null, result);
                if (errors) {
                    reject(convertError(errors[0]));
                } else {
                    resolve(result)
                }
            });
        });
    },

```

All the best.

**Comment by jbrodriguez** [comment]
@rhaker, you're absolutely right.

This is fixed in https://github.com/jbrodriguez/react-native-android-sqlite/commit/8b5d08c3c1a34464bb275821b39c1281ded8afdf .

Thanks a lot for raising the issue.
