### ISSUE TITLE
Callback with id 3: DBManager.exec() not found

### ISSUE THREAD

**Issue by happyEgg** [jbrodriguez/react-native-android-sqlite#4]
sqlite.init(databaseName).then((_) => {
            ToastAndroid.show("database initialized.", ToastAndroid.SHORT);
 }) 
 init can pass, but exec cannot pass, the result: Callback with id 3: DBManager.exec() not found

Do you have a idea?

**Comment by jbrodriguez** [comment]
It seems that the java code isn't being compiled.

Can you show the output for `$ adb logcat | grep 'SQLiteAssetHelper'`

Also when you run `$ react-native run-android`, what do the lines that begin with :react-native-android-sqlite say ?

**Comment by jbrodriguez** [comment]
@happyEgg also check the command you're sending to the sqlite.exec function.

Maybe a parameter is incorrectly written or something similar

**Comment by jbrodriguez** [comment]
Open a new issue if needed
